# PyTorch Basics

In [1]:
import torch
import numpy as np

## Tensor Allocation

In [2]:
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
ft


 1  2
 3  4
[torch.FloatTensor of size 2x2]

In [3]:
lt = torch.LongTensor([[1, 2],
                       [3, 4]])
lt


 1  2
 3  4
[torch.LongTensor of size 2x2]

In [4]:
bt = torch.ByteTensor([[1, 0],
                       [0, 1]])
bt


 1  0
 0  1
[torch.ByteTensor of size 2x2]

In [5]:
x = torch.FloatTensor(3, 2)
x


 0.0000e+00  2.0000e+00
-1.3843e-38 -1.5849e+29
 2.8026e-45  0.0000e+00
[torch.FloatTensor of size 3x2]

## NumPy Compatibility

In [6]:
x = np.array([[1, 2],
              [3, 4]])
print(x, type(x))
x = torch.from_numpy(x)
print(x, type(x))
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>

 1  2
 3  4
[torch.LongTensor of size 2x2]
 <class 'torch.LongTensor'>
[[1 2]
 [3 4]] <class 'numpy.ndarray'>


## Tensor Type-casting

In [13]:
ft.long()


 1  2
 3  4
[torch.LongTensor of size 2x2]

In [14]:
lt.float()


 1  2
 3  4
[torch.FloatTensor of size 2x2]

In [15]:
torch.FloatTensor([1, 0]).byte()


 1
 0
[torch.ByteTensor of size 2]

## Get Shape

In [9]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

print(x.size())
print(x.shape)

print(x.dim())
print(len(x.size()))

print(x.size(1))
print(x.shape[1])

print(x.size(-1))
print(x.shape[-1])

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])
3
3
2
2
2
2


## Tensor Manipulation

In [10]:
print(x.view(12)) # 12 = 3 * 2 * 2
print(x.view(-1))

print(x.view(3, 4)) # 3 * 4 = 3 * 2 * 2
print(x.view(3, -1))

print(x.view(3, 1, 4))
print(x.view(-1, 1, 4))

print(x.view(3, 2, 2, 1))


  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
[torch.FloatTensor of size 12]


  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
[torch.FloatTensor of size 12]


  1   2   3   4
  5   6   7   8
  9  10  11  12
[torch.FloatTensor of size 3x4]


  1   2   3   4
  5   6   7   8
  9  10  11  12
[torch.FloatTensor of size 3x4]


(0 ,.,.) = 
   1   2   3   4

(1 ,.,.) = 
   5   6   7   8

(2 ,.,.) = 
   9  10  11  12
[torch.FloatTensor of size 3x1x4]


(0 ,.,.) = 
   1   2   3   4

(1 ,.,.) = 
   5   6   7   8

(2 ,.,.) = 
   9  10  11  12
[torch.FloatTensor of size 3x1x4]


(0 ,0 ,.,.) = 
   1
   2

(0 ,1 ,.,.) = 
   3
   4

(1 ,0 ,.,.) = 
   5
   6

(1 ,1 ,.,.) = 
   7
   8

(2 ,0 ,.,.) = 
   9
  10

(2 ,1 ,.,.) = 
  11
  12
[torch.FloatTensor of size 3x2x2x1]



In [11]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]]])
print(x.size())

print(x.squeeze())
print(x.squeeze().size())

print(x.squeeze(0).size())
print(x.squeeze(1).size())

torch.Size([1, 2, 2])

 1  2
 3  4
[torch.FloatTensor of size 2x2]

torch.Size([2, 2])
torch.Size([2, 2])
torch.Size([1, 2, 2])


In [12]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
print(x.size())

print(x.unsqueeze(2))
print(x.unsqueeze(-1))
print(x.view(2, 2, 1))

torch.Size([2, 2])

(0 ,.,.) = 
  1
  2

(1 ,.,.) = 
  3
  4
[torch.FloatTensor of size 2x2x1]


(0 ,.,.) = 
  1
  2

(1 ,.,.) = 
  3
  4
[torch.FloatTensor of size 2x2x1]


(0 ,.,.) = 
  1
  2

(1 ,.,.) = 
  3
  4
[torch.FloatTensor of size 2x2x1]



## Slicing and Concatenation

In [16]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])
print(x.size())

torch.Size([3, 2, 2])


In [17]:
print(x[0])
print(x[0, :])
print(x[0, :, :])


 1  2
 3  4
[torch.FloatTensor of size 2x2]


 1  2
 3  4
[torch.FloatTensor of size 2x2]


 1  2
 3  4
[torch.FloatTensor of size 2x2]



In [16]:
print(x[-1])
print(x[-1, :])
print(x[-1, :, :])

tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])


In [17]:
print(x[:, 0, :])

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])


In [18]:
print(x[1:3, :, :].size())
print(x[:, :1, :].size())
print(x[:, :-1, :].size())

torch.Size([2, 2, 2])
torch.Size([3, 1, 2])
torch.Size([3, 1, 2])


In [19]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]])

print(x.size(), y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [20]:
z = torch.cat([x, y], dim=0)
print(z)
print(z.size())

z = torch.cat([x, y], dim=-1)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([6, 3])
tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


In [21]:
z = torch.stack([x, y])
print(z)
print(z.size())

z = torch.stack([x, y], dim=-1)
print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])
tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])
torch.Size([3, 3, 2])


Homework: 최대한 많은 방법으로 stack함수를 사용하지 않고 stack함수와 같은 결과가 나오도록 만들어보기.

## Arithmetic Operation (element-wise)

In [22]:
x = torch.FloatTensor([[4, 4],
                       [4, 4]])
y = torch.FloatTensor([[2, 2],
                       [2, 2]])

In [23]:
x + y

tensor([[6., 6.],
        [6., 6.]])

In [24]:
x - y

tensor([[2., 2.],
        [2., 2.]])

In [25]:
x * y

tensor([[8., 8.],
        [8., 8.]])

In [26]:
x / y

tensor([[2., 2.],
        [2., 2.]])

In [27]:
x**2

tensor([[16., 16.],
        [16., 16.]])

In [28]:
x**y

tensor([[16., 16.],
        [16., 16.]])

In [29]:
x.mul(y)

tensor([[8., 8.],
        [8., 8.]])

In [30]:
x.div(y)

tensor([[2., 2.],
        [2., 2.]])

## Inplace Operation

In [31]:
print(x)
print(x.mul(y))
print(x)
print(x.mul_(y))
print(x)

tensor([[4., 4.],
        [4., 4.]])
tensor([[8., 8.],
        [8., 8.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[8., 8.],
        [8., 8.]])
tensor([[8., 8.],
        [8., 8.]])


## Sum, Mean

In [32]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])

In [33]:
print(x.sum())
print(x.mean())

tensor(10.)
tensor(2.5000)


In [34]:
print(x.sum(dim=0))
print(x.sum(dim=-1))

tensor([4., 6.])
tensor([3., 7.])


## Matrix Multiplication

In [35]:
x = torch.FloatTensor([[1, 2],
                       [3, 4],
                       [5, 6]])
y = torch.FloatTensor([[1, 2],
                       [1, 2]])

print(x.size(), y.size())

torch.Size([3, 2]) torch.Size([2, 2])


In [36]:
z = torch.matmul(x, y)
print(z.size())

torch.Size([3, 2])


In [37]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4],
                        [5, 6]],
                       [[7, 8],
                        [9, 10],
                        [11, 12]],
                       [[13, 14],
                        [15, 16],
                        [17, 18]]])
y = torch.FloatTensor([[[1, 2, 2],
                        [1, 2, 2]],
                       [[1, 3, 3],
                        [1, 3, 3]],
                       [[1, 4, 4],
                        [1, 4, 4]]])

print(x.size(), y.size())

torch.Size([3, 3, 2]) torch.Size([3, 2, 3])


In [38]:
z = torch.bmm(x, y)
print(z.size())

torch.Size([3, 3, 3])


## Broadcast

In [39]:
x = torch.FloatTensor([[3, 3]])
y = torch.FloatTensor([[2, 2]])

print(x.size())
print(y.size())
print(x + y)

torch.Size([1, 2])
torch.Size([1, 2])
tensor([[5., 5.]])


In [40]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([3])

print(x.size())
print(y.size())
print(x + y)

torch.Size([1, 2])
torch.Size([1])
tensor([[4., 5.]])


In [41]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3], [4]])

print(x.size())
print(y.size())
print(x + y)

torch.Size([1, 2])
torch.Size([2, 1])
tensor([[4., 5.],
        [5., 6.]])


## Ones and Zeros

In [42]:
print(torch.ones(2, 3))
print(torch.zeros(2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [43]:
x = torch.FloatTensor(
    [[1, 2, 3], [4, 5, 6]]
)
print(x.size())

torch.Size([2, 3])


In [44]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


Homework: ones와 zeros를 사용하여 ones_like와 zeros_like를 구현하기